package tor

import (
	"fmt"
)

// generateTorrc renders the torrc content for the dedicated Tor process
// from Config, per AI.md PART 31 "getTorConfig". The hidden service itself
// is never described in torrc - it is created dynamically via the control
// protocol's ADD_ONION command - so this only configures daemon-level
// settings (ports, bandwidth, logging, relay/exit opt-out).
func generateTorrc(cfg Config) string {
	// Control connection always uses a runtime-selected localhost port -
	// never the system Tor default (9051), never hardcoded.
	controlConfig := "ControlPort 127.0.0.1:auto"

	// SocksPort: enabled (runtime port) only when outbound-via-Tor is
	// enabled; otherwise fully disabled - never the system Tor default
	// (9050).
	socksConfig := "SocksPort 0"
	if cfg.UseNetwork {
		socksConfig = "SocksPort auto"
	}

	safeLogging := "1"
	if !cfg.SafeLogging {
		safeLogging = "0"
	}

	// Monthly bandwidth accounting is only emitted when a real cap is
	// configured; "unlimited" (or empty) disables the accounting block
	// entirely.
	accountingConfig := ""
	if cfg.MaxMonthlyBandwidth != "" && cfg.MaxMonthlyBandwidth != "unlimited" {
		accountingConfig = fmt.Sprintf(`
# Monthly bandwidth limit
AccountingStart month 1 00:00
AccountingMax %s`, cfg.MaxMonthlyBandwidth)
	}

	return fmt.Sprintf(`# ============================================================
# Tor Configuration - Generated by server binary
# This file is PERSISTENT - it is not regenerated on normal startup.
# Manual edits may be overwritten when Tor config is changed via server.yml.
# ============================================================

# SOCKS port for outbound connections (0 = disabled, auto = runtime port)
# NEVER uses default port 9050 - runtime detection only
%s

# Control connection
# NEVER uses default port 9051 - uses runtime localhost port on all OSes
%s

# Security Hardening
SafeLogging %s

# Circuit limits
MaxCircuitDirtiness 600

# Bandwidth limits per second (from config)
BandwidthRate %s
BandwidthBurst %s
%s

# Disable unused features - not a relay or exit
ExitRelay 0
ExitPolicy reject *:*
ORPort 0
DirPort 0

# Hidden service optimizations (actual HS created via ADD_ONION)
HiddenServiceSingleHopMode 0

# Faster startup
FetchDirInfoEarly 1
FetchDirInfoExtraEarly 1

# Reduce memory usage
DisableDebuggerAttachment 1
`, socksConfig, controlConfig, safeLogging, cfg.BandwidthRate, cfg.BandwidthBurst, accountingConfig)
}
