# nginx proxy address - http://172.17.0.1:64580
# api - development

name: api

x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  api:
    image: ghcr.io/apimgr/api:devel
    container_name: api-app
    hostname: api
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      PORT: 80
      DEBUG: 1
      MODE: dev
      TZ: America/New_York
    volumes:
      - './volumes/config:/config:z'
      - './volumes/data:/data:z'
    ports:
      # Development: accessible from all interfaces, no 172.17.0.1 bind
      - '64580:80'
    healthcheck:
      test: /usr/local/bin/api --status
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    networks:
      - api

networks:
  api:
    name: api
    external: false
